package models

import "time"

// User represents a registered user in Finetic
type User struct {
	ID           string    `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"-"` // The "-" ensures the password hash is NEVER sent in JSON responses
	FirstName    string    `json:"first_name,omitempty"`
	LastName     string    `json:"last_name,omitempty"`
	PhoneNumber  string    `json:"phone_number,omitempty"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// Transaction represents a financial record (Income/Expense/M-Pesa)
type Transaction struct {
	ID                 string    `json:"id"`
	UserID             string    `json:"user_id"`
	CategoryID         *int      `json:"category_id,omitempty"` // Pointer because it can be NULL in DB
	Amount             int64     `json:"amount"`                // Stored in lowest denomination (e.g., cents)
	Type               string    `json:"type"`                  // e.g., "income", "expense"
	MpesaReceiptNumber *string   `json:"mpesa_receipt_number,omitempty"`
	SenderOrRecipient  string    `json:"sender_or_recipient,omitempty"`
	RawSMSData         string    `json:"raw_sms_data,omitempty"`
	TransactionDate    time.Time `json:"transaction_date"`
	CreatedAt          time.Time `json:"created_at"`
}

// AIInsight represents a personalized financial tip generated by your Python service
type AIInsight struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	InsightType string    `json:"insight"`
	Message     string    `json:"message"`
	IsRead      bool      `json:"is_read"`
	CreatedAt   time.Time `json:"created_at"`
}
